# 开发环境
spring:
  # nacos配置，需要改为服务器ip
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER}
        username: ${NACOS_USER}
        password: ${NACOS_PASSWORD}

  rabbitmq:
    host: ${RABBITMQ_SERVER}
    port: 5672
    virtual-host: /
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        acknowledge-mode: manual

  # db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_SERVER}:3306/product_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    hikari:
      max-lifetime: 300000         # 5分钟，单位毫秒
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 60000
      minimum-idle: 5
      maximum-pool-size: 20
      pool-name: HikariCP
  hikari:
    max-lifetime: 60000
    connection-test-query: SELECT 1  # MySQL 验证语句
  #  redis配置
  data:
    redis:
      host: ${REDIS_SERVER}
      port: 6300
      password: ${REDIS_PASSWORD}
#  锁配置 防止不同环境争抢一把锁
lock:
  prefix-key: dev

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: net.zicai.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: false

springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: net.zicai.controller
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true